name: GitHub Actions Demo 01
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
     - name: "Event Name"
       run:  echo "${{ github.event_name }}"
     - name: "Using checkout action"
       uses: actions/checkout@v4
     - name: "Repository Tree"
       run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
