name: my-action
on:
  push:
    branches: 
      - main
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Run my action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@thiagobfim'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
     
